### PR TITLE
Non-iOS Purple checkout flows (client-side)

### PR DESCRIPTION
**Pull request by danieldaquino**
## Summary

This PR implements the following:
- A significant refactor that splits some long source files into smaller reusable blocks that are **far** easier to work with
- Code deduplication as part of the above refactor
- Implementation of the OTP authentication on the Purple checkout, added as an option (users can choose which method to go with)
- Updates to outdated links and navigation flows.
- Other small fixes

## Checklist

- [X] I have read (or I am familiar with) the [Contribution Guidelines](../docs/CONTRIBUTING.md)
- [X] I have tested the changes in this PR
- [X] My PR is either small, or I have split it into smaller logical commits that are easier to review
- [X] I have added the signoff line to all my commits. See [Signing off your work](../docs/CONTRIBUTING.md#sign-your-work---the-developers-certificate-of-origin)
- [ ] I have added appropriate changelog entries for the changes in this PR. See [Adding changelog entries](../docs/CONTRIBUTING.md#add-changelog-changed-changelog-fixed-etc)
    - [X] I do not need to add a changelog entry. Reason: We don't strictly keep track of changelog on this repo
- [X] I have added appropriate `Closes:` or `Fixes:` tags in the commit messages wherever applicable, or made sure those are not needed. See [Submitting patches](https://github.com/damus-io/damus/blob/master/docs/CONTRIBUTING.md#submitting-patches) **— I have not added this because the issue also depends on https://github.com/damus-io/api/pull/11**

## Test report

**Damus:** 1.10.1 (1) `f92509fd`
**Device:** iPhone 13 mini
**iOS:** 18.0
**Browser:** Multiple browsers, see steps for details
**damus-api:** `03e1e90cffd370252826ccb2934320f120b15426` with Node v22.9.0
    - **Note:** This was a WIP version of `8bdbd179536da01c3a74b1c8cb5cd7427437c672` that is identical in almost every way except the LN node connection params, which had been changed during development to work with node.js v22.9.0, but has now been reverted for node v18 LTS compatibility. A supplemental test report is attached below to cover the invalidated portion of the test
**damus-website:** `1b6209afc40c463a04d7267a155e840736301c39`
**LN wallet:** coinos.io
**Setup:**
- Website running from a static http server (`python3 -m http.server`) using a development build with our custom test env details (`npm run build-dev`)
- Local server
- Local server database wiped at the start for testing purposes.
- Server and website in a LAN-like VPN setup
- Damus iOS setup with a test Purple environment, pointing to the test server
- LN node similar (or same) as used in production

**Steps:**
1. Clicked all major internal links around the website to ensure there are no broken links
2. Verified initial LN checkout (i.e. new user signup) using the desktop Safari and Damus iOS as a verification method works
    - UI looks good
    - Verification flow works
    - Reloading page after npub verification is stable (makes verified profile show up)
    - LN payment works
    - Reloading page after LN payment is stable (nothing is lost)
    - All of this setup works with doing checkout on the desktop and using QR codes to use Damus iOS for verification
    - Checkout page looks good on desktop
    - Welcome and setup in-app works
3. Verified renewing with Damus iOS works:
	- Doing the whole flow on iOS (same device for checkout and verification) works
	- Renewal works
	- Checkout page looks good on mobile
4. Verified initial LN checkout (i.e. new user signup) using iOS Safari and OTP as a verification method works
    - UI looks good on iOS
    - Entering incorrect OTP code correctly shows user about the mismatch, and gives them a change to resend OTP code.
    - Resending OTP code works
    - Verification flow via OTP works
    - Reloading page after npub verification is stable (makes verified profile show up)
    - LN payment works
    - Reloading page after LN payment is stable (nothing is lost)
    - Welcome screen and account details screen after payment works (on iOS)
5. Verified renewing using Desktop Firefox and OTP as a verification method works
	- Checkout looks good on Firefox
	- Existing account detection works
	- OTP troubleshooting message appears after 10 seconds of having an empty OTP, and disappears upon typing
	- LN payment works
	- Refreshing page after LN payment is stable
	- Welcome message and account message flow via web works well and looks good on Firefox
	- Checked on Damus iOS that account details match
6. Logout works
7. Login still works (Tested on Firefox)
	- Account detection works (If no account exists, user is recommended to purchase/join Purple)
	- Invalid OTP + resend flow works
	- Successful OTP finishes login and takes user to the account page as expected
8. Purple landing page shows more relevant options when user is logged in

**Results:**
- [X] PASS
- [ ] Partial PASS
  - Details: n/a

## Supplemental test report

This supplemental test report is needed to cover a portion of the previous test that was invalidated due to a small code change on the server-side.

**Damus:** 1.10.1 (1) `f92509fd`
**Device:** iPhone 13 mini
**iOS:** 18.0
**Browser:** Safari
**damus-api:** `8bdbd179536da01c3a74b1c8cb5cd7427437c672` with Node v18.20.4, running on NixOS
**damus-website:** `1b6209afc40c463a04d7267a155e840736301c39`
**LN wallet:** coinos.io
**Setup:**
- Same as the previous setup
**Steps:**
1. Delete local DB
2. Go through checkout process using Damus iOS as the auth method. Ensure that LN invoice is generated, payment is detected, and otherwise flow goes smoothly 
3. Go through the checkout process again (renewal), this time using OTP as the auth method. Ensure that LN invoice is generated, payment is detected, and otherwise flow goes smoothly.

**Results:**
- [X] PASS
- [ ] Partial PASS
  - Details: n/a

## Other notes

These changes rely on some API changes on the server side. The backend should be updated first when deploying: https://github.com/damus-io/api/pull/11

### CODE REVIEW

**Comment by danieldaquino** [comment]
@jb55 quick note before we publish this website version. I think some of the changes you made to the notedeck page have not been pushed, they don't seem to be present in github. You may want to push those changes upstream from where you made them to avoid losing them.

**Comment by danieldaquino** [comment]
@jb55 please let me know if you have any questions or concerns with this PR, thanks!

**Comment by jb55** [comment]
On Fri, Oct 18, 2024 at 11:13:08AM -0700, Daniel D’Aquino wrote:
>@jb55 quick note before we publish this website version. I think some of the changes you made to the notedeck page have not been pushed, they don't seem to be present in github. You may want to push those changes upstream from where you made them to avoid losing them.

the changes were minimal, I don't mind losing them. I can't find the
changes

**Comment by jb55** [comment]
On Fri, Oct 18, 2024 at 11:13:54AM -0700, Daniel D’Aquino wrote:
>@jb55 please let me know if you have any questions or concerns with this PR, thanks!
let's merge it!

**Pull request merged**
