### PR TITLE
fix capitalization

### PR DESCRIPTION
**Pull request by hecov**
Before: 
image

After: 
image

### CODE REVIEW

**Comment by hecov** [comment]
By the way, the capitalization that I fixed is the "truly Free" to "truly free"

**Comment by jb55** [comment]
On Mon, Feb 26, 2024 at 09:12:03PM -0800, Hecov wrote:
>By the way, the capitalization that I fixed is the "truly Free" to "truly free"

weird I somehow missed this PR, thanks for the ping

**Comment by jb55** [comment]
On Thu, Feb 01, 2024 at 05:34:08AM +0000, Hecov wrote:
>Closes: https://github.com/damus-io/website/pull/18
>---
> content/compiled-locales/en.json     | 2 +-
> content/locales/en.json              | 2 +-
> src/components/sections/Benefits.tsx | 2 +-
> 3 files changed, 3 insertions(+), 3 deletions(-)
>
>diff --git a/content/compiled-locales/en.json b/content/compiled-locales/en.json
>index 5aa46d6..636b6ca 100644
>--- a/content/compiled-locales/en.json
>+++ b/content/compiled-locales/en.json
>@@ -56,7 +56,7 @@
>   "benefits.description": [
>     {
>       "type": 0,
>-      "value": "Damus is built on Nostr, a decentralized and open social network protocol. Without ads, toxic algorithms, or censorship, Damus gives you access to the social network that a truly Free and healthy society needs — and deserves."
>+      "value": "Damus is built on Nostr, a decentralized and open social network protocol. Without ads, toxic algorithms, or censorship, Damus gives you access to the social network that a truly free and healthy society needs — and deserves."
>     }
>   ],
>   "benefits.headline": [
>diff --git a/content/locales/en.json b/content/locales/en.json
>index 4a54408..414baf4 100644
>--- a/content/locales/en.json
>+++ b/content/locales/en.json
>@@ -27,7 +27,7 @@
>     "string": "Free speech meets Free money"
>   },
>   "benefits.description": {
>-    "string": "Damus is built on Nostr, a decentralized and open social network protocol. Without ads, toxic algorithms, or censorship, Damus gives you access to the social network that a truly Free and healthy society needs — and deserves."
>+    "string": "Damus is built on Nostr, a decentralized and open social network protocol. Without ads, toxic algorithms, or censorship, Damus gives you access to the social network that a truly free and healthy society needs — and deserves."
>   },
>   "benefits.headline": {
>     "string": "You deserve to be Free."
>diff --git a/src/components/sections/Benefits.tsx b/src/components/sections/Benefits.tsx
>index 4842ce7..29fb518 100644
>--- a/src/components/sections/Benefits.tsx
>+++ b/src/components/sections/Benefits.tsx
>@@ -49,7 +49,7 @@ export function Benefits({ className }: { className?: string }) {
>                             { intl.formatMessage({ id: "benefits.subheadline", defaultMessage: "With Damus, you are in control." }) }
>                         </motion.h3>
>                         <motion.div className="text-white/60 text-xl text-center max-w-2xl mb-6 mt-6 break-keep">
>-                            { intl.formatMessage({ id: "benefits.description", defaultMessage: "Damus is built on Nostr, a decentralized and open social network protocol. Without ads, toxic algorithms, or censorship, Damus gives you access to the social network that a truly Free and healthy society needs — and deserves." }) }
>+                            { intl.formatMessage({ id: "benefits.description", defaultMessage: "Damus is built on Nostr, a decentralized and open social network protocol. Without ads, toxic algorithms, or censorship, Damus gives you access to the social network that a truly free and healthy society needs — and deserves." }) }

Seems to be some duplication here, is there a way to make it use the
english translation as the default? cc'ing Daniel

**Comment by jb55** [comment]
Thanks! picked into 4a18875581de

**Pull request closed without merging**
